apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-projects
  namespace: mazanex
  labels:
    app: ms-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-projects
  template:
    metadata:
      labels:
        app: ms-projects
    spec:
      containers:
        - name: ms-projects
          image: mazanex-ms-projects:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: mazanex-config
            - secretRef:
                name: mazanex-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-projects-service
  namespace: mazanex
spec:
  selector:
    app: ms-projects
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP