apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-projects
  namespace: mazanex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-projects
  template:
    metadata:
      labels:
        app: ms-projectss
    spec:
      containers:
      - name: ms-projects
        image: mazanex-projects-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: projects-config
        - secretRef:
            name: projects-secrets
        env:
        - name: SENTRY_DSN
          value: ""