apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-projects-hpa
  namespace: mazanex
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-projects
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70