apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-projects
  namespace: mazanex
spec:
  selector:
    matchLabels:
      app: mysql-projects
  template:
    metadata:
      labels:
        app: mysql-projects
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: db_projects
        - name: MYSQL_ROOT_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-projects-service
  namespace: mazanex
spec:
  selector:
    app: mysql-projects
  ports:
  - port: 3306