apiVersion: v1
kind: Secret
metadata:
  name: projects-secrets
  namespace: mazanex
type: Opaque
data:
  # Base64 para 'root'
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cm9vdA==