services:
  # ==========================================
  # 1. BASE DE DATOS (MySQL)
  # ==========================================
  db:
    image: mysql:8.0
    container_name: mazanex-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    networks:
      - mazanex-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # ==========================================
  # 2. BFF (KrakenD)
  # ==========================================
  bff:
    build:
      context: ./backend/bff
      dockerfile: Dockerfile
    container_name: mazanex-bff
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - profile-service
      - publications-service
      - ranking-service
    networks:
      - mazanex-network

  # ==========================================
  # 3. MICROSERVICIOS BACKEND
  # ==========================================
  auth-service:
    build:
      context: ./backend/ms-auth
      dockerfile: Dockerfile
    container_name: mazanex-auth
    ports:
      - "8081:8081"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=auth_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8081
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  profile-service:
    build:
      context: ./backend/ms-profile
      dockerfile: Dockerfile
    container_name: mazanex-profile
    ports:
      - "8082:8082"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=profile_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8082
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  publications-service:
    build:
      context: ./backend/ms-publications
      dockerfile: Dockerfile
    container_name: mazanex-publications
    ports:
      - "8083:8083"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=publications_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8083
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  ranking-service:
    build:
      context: ./backend/ms-ranking
      dockerfile: Dockerfile
    container_name: mazanex-ranking
    ports:
      - "8084:8084"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=ranking_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8084
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  projects-service:
    build:
      context: ./backend/ms-projects
      dockerfile: Dockerfile
    container_name: mazanex-projects
    ports:
      - "8085:8085"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=db_projects
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8085
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  # ==========================================
  # 4. FRONTEND (Next.js)
  # ==========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mazanex-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:8080
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - bff
    networks:
      - mazanex-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

# ==========================================
  # CONTENEDORES DE INFRAESTRUCTURA GLITCHTIP
  # ==========================================
  glitchtip:
    image: glitchtip/glitchtip:latest
    container_name: mazanex-glitchtip
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - glitchtip-db
      - glitchtip-redis
    environment:
      - DATABASE_URL=postgres://glitchtip:password@glitchtip-db:5432/glitchtip
      - GLITCHTIP_DOMAIN=http://localhost:8000
      - GLITCHTIP_EMBED_WORKER=true          # Obligatorio en minúsculas para activar el worker
      - SERVER_ROLE=all_in_one               
      - GLITCHTIP_ENABLE_LOGS=True         
      - REDIS_URL=redis://glitchtip-redis:6379/0
      - VALKEY_URL=redis://glitchtip-redis:6379/0
      - SECRET_KEY=una-key-muy-segura-y-secreta-123
      - DEFAULT_FROM_EMAIL=tu-email@dominio.com
    networks:
      - mazanex-network # Asegúrate de que use el mismo nombre de red que tus otros servicios

  glitchtip-db:
    image: postgres:17-alpine
    container_name: mazanex-glitchtip-db
    environment:
      - POSTGRES_USER=glitchtip
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glitchtip
    networks:
      - mazanex-network

  glitchtip-redis:
    image: redis:7-alpine
    container_name: mazanex-glitchtip-redis
    networks:
      - mazanex-network

networks:
  mazanex-network:
    driver: bridge

volumes:
  db_data: {}