services:
  # ==========================================
  # 1. BASE DE DATOS (MySQL)
  # ==========================================
  db:
    image: mysql:8.0
    container_name: mazanex-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    networks:
      - mazanex-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # ==========================================
  # 2. BFF (KrakenD)
  # ==========================================
  bff:
    build:
      context: ./backend/bff
      dockerfile: Dockerfile
    container_name: mazanex-bff
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - profile-service
      - publications-service
      - ranking-service
    networks:
      - mazanex-network

  # ==========================================
  # 3. MICROSERVICIOS BACKEND
  # ==========================================
  auth-service:
    build:
      context: ./backend/ms-auth
      dockerfile: Dockerfile
    container_name: mazanex-auth
    ports:
      - "8081:8081"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=auth_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8081
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  profile-service:
    build:
      context: ./backend/ms-profile
      dockerfile: Dockerfile
    container_name: mazanex-profile
    ports:
      - "8082:8082"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=profile_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8082
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
      # Cambia "TU_ID" por el número que te dé GlitchTip al crear el proyecto
      - SENTRY_DSN=http://llave_publica_aqui@mazanex-glitchtip-web:8000/TU_ID
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  publications-service:
    build:
      context: ./backend/ms-publications
      dockerfile: Dockerfile
    container_name: mazanex-publications
    ports:
      - "8083:8083"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=publications_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8083
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  ranking-service:
    build:
      context: ./backend/ms-ranking
      dockerfile: Dockerfile
    container_name: mazanex-ranking
    ports:
      - "8084:8084"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=ranking_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8084
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  projects-service:
    build:
      context: ./backend/ms-projects
      dockerfile: Dockerfile
    container_name: mazanex-projects
    ports:
      - "8085:8085"
    environment:
      - MYSQLHOST=db
      - MYSQLPORT=3306
      - MYSQLDATABASE=db_projects
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - PORT=8085
      - JWT_SECRET=f8a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mazanex-network

  # ==========================================
  # 4. FRONTEND (Next.js)
  # ==========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mazanex-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:8080
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_OPTIONS=--max-old-space-size=2048
    depends_on:
      - bff
    networks:
      - mazanex-network
    
    #volumes:
    
    #  - ./frontend:/app
     # - /app/node_modules

  # ==========================================
  # 5. GLITCHTIP LOCAL
  # ==========================================
  postgres-glitchtip:
    image: postgres:15-alpine
    container_name: mazanex-glitchtip-db
    environment:
      POSTGRES_DB: glitchtip
      POSTGRES_USER: glitchtip
      POSTGRES_PASSWORD: password_seguro
    networks:
      - mazanex-network
    volumes:
      - glitchtip_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-glitchtip:
    image: redis:alpine
    container_name: mazanex-glitchtip-redis
    networks:
      - mazanex-network
    restart: unless-stopped

  glitchtip-web:
    image: glitchtip/glitchtip
    container_name: mazanex-glitchtip-web
    depends_on:
      - postgres-glitchtip
      - redis-glitchtip
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://glitchtip:password_seguro@postgres-glitchtip:5432/glitchtip
      REDIS_URL: redis://mazanex-glitchtip-redis:6379
      SECRET_KEY: clave_secreta_mazanex_muy_larga
      PORT: 8000
      GLITCHTIP_DOMAIN: http://localhost:8000
      ENABLE_USER_REGISTRATION: "True"
    networks:
      - mazanex-network
    restart: unless-stopped

  glitchtip-worker:
    image: glitchtip/glitchtip
    container_name: mazanex-glitchtip-worker
    command: ./bin/run-celery-with-beat.sh
    depends_on:
      - postgres-glitchtip
      - redis-glitchtip
    environment:
      DATABASE_URL: postgres://glitchtip:password_seguro@postgres-glitchtip:5432/glitchtip
      REDIS_URL: redis://mazanex-glitchtip-redis:6379
      SECRET_KEY: clave_secreta_mazanex_muy_larga
    networks:
      - mazanex-network
    restart: unless-stopped

networks:
  mazanex-network:
    driver: bridge

volumes:
  db_data:
  glitchtip_pg_data: