apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mazanex-mysql-pvc
  labels:
    app: mazanex-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: your-storage-class  # Opcional: ajusta según tu cluster
