apiVersion: v1
kind: Secret
metadata:
  name: mazanex-mysql-secret
  labels:
    app: mazanex-mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: mazanex_db
  MYSQL_USER: root
  MYSQL_PASSWORD: root
