apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-profile
  namespace: mazanex
  labels:
    app: ms-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-profile
  template:
    metadata:
      labels:
        app: ms-profile
    spec:
      containers:
        - name: ms-profile
          image: mazanex-profile-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: profile-config
            - secretRef:
                name: profile-secrets
          env:
            - name: SENTRY_DSN
              value: ""
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---