apiVersion: v1
kind: ConfigMap
metadata:
  name: ranking-config
  namespace: mazanex
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-ranking-service:3306/db_ranking
  SPRING_JPA_HIBERNATE_DDL_AUTO: update