apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-ranking
  namespace: mazanex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-ranking
  template:
    metadata:
      labels:
        app: ms-ranking
    spec:
      containers:
      - name: ms-ranking
        image: mazanex-ranking-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: ranking-config
        - secretRef:
            name: ranking-secrets