apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: mazanex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: mazanex-bff:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # Puerto estándar de KrakenD
        volumeMounts:
        - name: config-volume
          mountPath: /etc/krakend/krakend.json
          subPath: krakend.json
      volumes:
      - name: config-volume
        configMap:
          name: bff-config