apiVersion: v1
kind: ConfigMap
metadata:
  name: mazanex-auth-config
  labels:
    app: mazanex-auth
data:
  MYSQLHOST: mysql
  MYSQLPORT: "3306"
  MYSQLDATABASE: mazanex_db
  MYSQLUSER: root
  PORT: "8081"
