apiVersion: v1
kind: ConfigMap
metadata:
  name: mazanex-config
  namespace: mazanex
data:
  MYSQLHOST: "mysql-service" # Nombre del servicio de la BD en K8s
  MYSQLPORT: "3306"
  MYSQLDATABASE: "db_auth"
  PROFILE_SERVICE_URL: "http://ms-profile.mazanex:8082"