apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
  namespace: mazanex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: mazanex-ms-auth:latest # Cambiado a latest o versión específica
          imagePullPolicy: IfNotPresent # Recomendado para entornos reales
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: mazanex-config
            - secretRef:
                name: mazanex-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health # Recomendado usar Actuator para probes
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10