server:
  port: 8080 # El Gateway será la puerta principal de entrada

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Solucionamos el CORS aquí mismo para que Next.js no tenga problemas
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      
      # Aquí definimos hacia dónde va cada petición
      routes:
        - id: ms-auth
          uri: http://localhost:8081 # Puerto de tu ms-auth
          predicates:
            - Path=/api/auth/**
            
        - id: ms-profile
          uri: http://localhost:8082 # Puerto de tu ms-profile
          predicates:
            - Path=/api/profile/**
            
        - id: ms-ranking
          uri: http://localhost:8084 # Puerto de tu ms-ranking
          predicates:
            - Path=/api/ranking/**
            
        - id: ms-publications
          uri: http://localhost:8083 # Puerto de tu ms-publications
          predicates:
            - Path=/api/publications/**