name: CI - Publications Service

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'publications-service/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'publications-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./publications-service

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Ejecutar pruebas de Publications
      run: mvn clean test