apiVersion: v1
kind: ConfigMap
metadata:
  name: mazanex-profile-config
  labels:
    app: mazanex-profile
data:
  MYSQLHOST: mysql
  MYSQLPORT: "3306"
  MYSQLDATABASE: mazanex_db
  MYSQLUSER: root
  PORT: "8082"
