apiVersion: v1
kind: ConfigMap
metadata:
  name: publications-config
  namespace: mazanex
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-publications-service:3306/db_publications
  SPRING_JPA_HIBERNATE_DDL_AUTO: update