apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-publications
  namespace: mazanex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-publications
  template:
    metadata:
      labels:
        app: ms-publications
    spec:
      containers:
      - name: ms-publications
        image: mazanex-publications-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: publications-config
        - secretRef:
            name: publications-secrets