name: CI - Infraestructura
on: [push]
jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Up
        run: docker compose up -d
      - name: Wait for services
        run: sleep 30 # Tiempo para asegurar el healthcheck de la BD
      - name: Check Environment
        run: |
          chmod +x check-env.sh
          ./check-env.sh